import { SpeedInsights } from "@vercel/speed-insights/next"
import Nav from "../component/Nav/Nav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Nav />
        <div style={{paddingTop: "3rem"}}>
        {children}
        </div>
      </body>
    </html>
  )
}
