import { SpeedInsights } from "@vercel/speed-insights/next"
import Nav from "../component/Nav/Nav"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>/
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href='https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&family=Playfair+Display:ital,wght@0,400..900;1,400..900&display=swap' rel="stylesheet" />
      </head>
      <body>
        <Nav />
        <div style={{paddingTop: "3rem"}}>
        {children}
        </div>
      </body>
    </html>
  )
}
